"""empty message

Revision ID: 68922558716
Revises: None
Create Date: 2015-01-19 00:10:30.961507

"""

# revision identifiers, used by Alembic.
revision = '68922558716'
down_revision = None

from alembic import op
import sqlalchemy as sa

from rumster.db import types


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', types.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', types.UUID(), nullable=False),
    sa.Column('email', sa.Unicode(120), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_series',
    sa.Column('player_id', types.UUID(), nullable=True),
    sa.Column('series_id', types.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('rounds',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', types.UUID(), nullable=False),
    sa.Column('series_id', types.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_stats',
    sa.Column('id', types.UUID(), nullable=False),
    sa.Column('round_id', types.UUID(), nullable=True),
    sa.Column('player_id', types.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_stats')
    op.drop_table('rounds')
    op.drop_table('player_series')
    op.drop_table('players')
    op.drop_table('series')
    ### end Alembic commands ###